### ISSUE TITLE
Critère 12.7 : place du lien d'accès rapide à la zone de contenu principal dans le code HTML

### ISSUE THREAD

**Issue by inseo** [accessibility-luxembourg/ReferentielAccessibiliteWeb#3]
Les techniques [G1](https://www.w3.org/WAI/WCAG21/Techniques/general/G1.html) et [G124](https://www.w3.org/WAI/WCAG22/Techniques/general/G124.html) qui permettent de valider le [critère 2.4.1 des WCAG](https://www.w3.org/WAI/WCAG22/quickref/?versions=2.1&showtechniques=241#bypass-blocks) demandent à ce que le lien d'accès rapide au contenu (ou à une partie de ce dernier) soit le premier élément tabulable de la page :

__Technique G1__
> Check that a link is the first focusable control on the Web page.

__Technique G124 :__
> For each link in the set of links provided for this purpose:
>    Check that the only controls in the Web page that precede the link are other links in the set. 

Le RAWeb, pour sa part, est moins exigeant.    
Le [test 12.7.2](https://accessibilite.public.lu/fr/raweb1/criteres.html#test-12-7-2) demande simplement à vérifier que : 
> Le lien est situé à la même place dans la présentation.
> Le lien se présente toujours dans le même ordre relatif dans le code source.

De fait, un bandeau de cookies contenant des boutons d'acceptation ou de paramétrage placés avant les liens d'accès rapides sont conformes RAWeb mais non conformes WCAG.

**Comment by AlainVagner** [comment]
Dans notre compréhension, les techniques G1 et G124 sont des [techniques suffisantes](https://www.w3.org/WAI/WCAG21/Understanding/understanding-techniques#sufficient-techniques). Si elles sont implémentées, alors le critère est validé. Si elles ne sont pas implémentées, alors cela ne veut pas dire que le critère est invalidé.

Concernant les bandeaux de cookies, la question est pertinente. 
On peut estimer qu'il est préférable qu'ils soient les premiers à recevoir le focus avant toute autre navigation, afin d'informer l'utilisateur avant d'accéder à tout contenu. 
Le critère 2.4.1 est formulé ainsi : "Un mécanisme permet de contourner les blocs de contenu qui sont répétés sur plusieurs pages Web."
Peut-on considérer le bandeau de cookies comme un élément répété sur plusieurs pages Web ? Dès lors qu'on a saisi ses choix, il n'apparaît plus.
Donc il serait possible que le bandeau de cookies, quand il apparaît, soit le premier élément tabulable tout en restant conforme au WCAG, suivant cette interprétation.

**Comment by inseo** [comment]
Si on part sur cette interprétation, effectivement l'implémentation est conforme WCAG. :)

Dans mon esprit, le problème du critère 12.7 du RAWeb -tel qu'il est formulé- était qu'il peut laisser à penser que sa validation entraîne _de facto_ la validation du critère 2.4.1 des WCAG. Ce qui n'est pas le cas…   
Mais la validation du critère 12.6 du RAWeb via la technique [ARIA11](https://www.w3.org/WAI/WCAG21/Techniques/aria/ARIA11) ou [H69](https://www.w3.org/WAI/WCAG21/Techniques/html/H69) par exemple, permet également de valider le critère 2.4.1.

Du coup, ma remarque est non fondée. :)
