### ISSUE TITLE
Developer Language Accessibility: Establishing English as the Standard Language

### ISSUE THREAD

**Issue by MentalGear** [accessibility-luxembourg/ReferentielAccessibiliteWeb#8]
Thank you for your work on improving accessibility - it's much appreciated!

However, to ensure consistency and adherence to international IT standards, please consider using English as the default language across both source-control (Readme) and your website.

Many developers and QA people working in the greater region are non-French speakers. By limiting accessibility resources to French, you exclude a broad audience and reduce the potential for widespread adoption — something that works against your mission of promoting accessibility.

English is the standard for technical documentation, code comments, and specifications, and helps ensure your project is accessible to a broader, global audience.

Thank you for making these updates and incorporating this change to English!

**Comment by AlainVagner** [comment]
Thank you for your message. We are a public administration and as such we must use one of our official national languages. You can use the [European standard EN 301 549](https://www.etsi.org/deliver/etsi_en/301500_301599/301549/03.02.01_60/en_301549v030201p.pdf) in Luxembourg without any issue, there is no obligation to use our resources.

**Comment by AlainVagner** [comment]
A translation of all the content in English is now available in this repository and on our website:
https://accessibilite.public.lu/en/raweb1/criteres.html

**Comment by MentalGear** [comment]
Wow, thank you - that's much appreciated!
